Update build_and_deploy.yml

diff --git a/.github/workflows/build_and_deploy.yml b/.github/workflows/build_and_deploy.yml
--- a/.github/workflows/build_and_deploy.yml
+++ b/.github/workflows/build_and_deploy.yml
@@ -74,99 +74,98 @@ jobs:
           name: compiled-backend
           path: target/*.jar
 
-build-artifact:
-  name: Build AMI
-  needs: compile-backend
-  runs-on: ubuntu-latest
-  outputs:
-        version_fingerprint: ${{ steps.hcp.outputs.version_fingerprint }}
-        ami_id: ${{ steps.ami.outputs.ami_id }}
-  if: github.event.inputs.run_update_asg_only != 'true' && github.event.inputs.use_default_ami != 'true'
-  steps:
-   - name: Checkout Repository
-     uses: actions/checkout@v4
+  build-artifact:
+   name: Build AMI
+   needs: compile-backend
+   runs-on: ubuntu-latest
+   outputs:
+    version_fingerprint: ${{ steps.hcp.outputs.version_fingerprint }}
+    ami_id: ${{ steps.ami.outputs.ami_id }}
+    if: github.event.inputs.run_update_asg_only != 'true' && github.event.inputs.use_default_ami != 'true'
+   steps:
+    - name: Checkout Repository
+      uses: actions/checkout@v4
+    
+    - name: Configure AWS Credentials
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: il-central-1
+    
+    - name: Ensure backend-jar directory exists
+      run: mkdir -p ./backend-jar
 
-      
-   - name: Configure AWS Credentials
-     uses: aws-actions/configure-aws-credentials@v4
-     with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: il-central-1
-      
-   - name: Ensure backend-jar directory exists
-     run: mkdir -p ./backend-jar
+    - name: Download compiled JAR
+      uses: actions/download-artifact@v2
+      with:
+        name: compiled-backend
+        path: ./backend-jar
 
-   - name: Download compiled JAR
-     uses: actions/download-artifact@v2
-     with:
-          name: compiled-backend
-          path: ./backend-jar
+    - name: Check backend-jar content
+      run: |
+        echo "Current directory:"
+        pwd
+        echo "Contents of current directory:"
+        ls -la
+        echo "Contents of ./backend-jar:"
+        ls -la ./backend-jar
+        echo "JAR file details:"
+        find ./backend-jar -name "*.jar" -type f -exec ls -l {} \;
+    
+    - name: Packer Init
+      run: packer init .
 
-   - name: Check backend-jar content
-     run: |
-          echo "Current directory:"
-          pwd
-          echo "Contents of current directory:"
-          ls -la
-          echo "Contents of ./backend-jar:"
-          ls -la ./backend-jar
-          echo "JAR file details:"
-          find ./backend-jar -name "*.jar" -type f -exec ls -l {} \;
-      
-   - name: Packer Init
-     run: packer init .
-
-   - name: Get latest AMI from Launch Template
-     run: |
-          LATEST_LT_VERSION=$(aws ec2 describe-launch-template-versions \
-            --launch-template-name "${{ env.LAUNCH_TEMPLATE_NAME }}" \
-            --versions '$Latest' \
-            --query 'LaunchTemplateVersions[0].VersionNumber' \
-            --output text)
-          LATEST_AMI=$(aws ec2 describe-launch-template-versions \
-            --launch-template-name "${{ env.LAUNCH_TEMPLATE_NAME }}" \
-            --versions $LATEST_LT_VERSION \
-            --query 'LaunchTemplateVersions[0].LaunchTemplateData.ImageId' \
-            --output text)
-          echo "LATEST_AMI=$LATEST_AMI" >> $GITHUB_ENV
-      
-   - name: Packer Build
-     run: |
-          JAR_FILE=$(find ./backend-jar -name "*.jar" -type f)
-          if [ -z "$JAR_FILE" ]; then
-            echo "Error: No JAR file found"
-            exit 1
-          fi
-          echo "Using JAR file: $JAR_FILE"
-          packer build \
-            -var "SSH_PACKER=${{ secrets.SSH_PACKER }}" \
-            -var "SSH_PACKER_PUB=${{ secrets.SSH_PACKER_PUB }}" \
-            -var "COMPILED_JAR_PATH=$JAR_FILE" \
-            -var "source_ami=${{ env.LATEST_AMI }}" \
-            .
-      
-   - name: Check backend-jar content after Packer
-     run: |
-          echo "Contents of ./backend-jar after Packer:"
-          ls -l ./backend-jar
-      
-   - name: Get HCP Packer version fingerprint from Packer Manifest
-     id: hcp
-     run: |
-          last_run_uuid=$(jq -r '.last_run_uuid' "./packer_manifest.json")
-          build=$(jq -r '.builds[] | select(.packer_run_uuid == "'"$last_run_uuid"'")' "./packer_manifest.json")
-          version_fingerprint=$(echo "$build" | jq -r '.custom_data.version_fingerprint')
-          echo "version_fingerprint=$version_fingerprint" >> $GITHUB_OUTPUT
-      
-   - name: Get AMI ID from Packer Manifest
-     id: ami
-     run: |
-          last_run_uuid=$(jq -r '.last_run_uuid' "./packer_manifest.json")
-          build=$(jq -r '.builds[] | select(.packer_run_uuid == "'"$last_run_uuid"'")' "./packer_manifest.json")
-          ami_id=$(echo "$build" | jq -r '.artifact_id' | cut -d':' -f2)
-          echo "ami_id=$ami_id" >> $GITHUB_OUTPUT
-          echo "AMI ID from Packer build: $ami_id"
+    - name: Get latest AMI from Launch Template
+      run: |
+        LATEST_LT_VERSION=$(aws ec2 describe-launch-template-versions \
+          --launch-template-name "${{ env.LAUNCH_TEMPLATE_NAME }}" \
+          --versions '$Latest' \
+          --query 'LaunchTemplateVersions[0].VersionNumber' \
+          --output text)
+        LATEST_AMI=$(aws ec2 describe-launch-template-versions \
+          --launch-template-name "${{ env.LAUNCH_TEMPLATE_NAME }}" \
+          --versions $LATEST_LT_VERSION \
+          --query 'LaunchTemplateVersions[0].LaunchTemplateData.ImageId' \
+          --output text)
+        echo "LATEST_AMI=$LATEST_AMI" >> $GITHUB_ENV
+    
+    - name: Packer Build
+      run: |
+        JAR_FILE=$(find ./backend-jar -name "*.jar" -type f)
+        if [ -z "$JAR_FILE" ]; then
+          echo "Error: No JAR file found"
+          exit 1
+        fi
+        echo "Using JAR file: $JAR_FILE"
+        packer build \
+          -var "SSH_PACKER=${{ secrets.SSH_PACKER }}" \
+          -var "SSH_PACKER_PUB=${{ secrets.SSH_PACKER_PUB }}" \
+          -var "COMPILED_JAR_PATH=$JAR_FILE" \
+          -var "source_ami=${{ env.LATEST_AMI }}" \
+          .
+    
+    - name: Check backend-jar content after Packer
+      run: |
+        echo "Contents of ./backend-jar after Packer:"
+        ls -l ./backend-jar
+    
+    - name: Get HCP Packer version fingerprint from Packer Manifest
+      id: hcp
+      run: |
+        last_run_uuid=$(jq -r '.last_run_uuid' "./packer_manifest.json")
+        build=$(jq -r '.builds[] | select(.packer_run_uuid == "'"$last_run_uuid"'")' "./packer_manifest.json")
+        version_fingerprint=$(echo "$build" | jq -r '.custom_data.version_fingerprint')
+        echo "version_fingerprint=$version_fingerprint" >> $GITHUB_OUTPUT
+    
+    - name: Get AMI ID from Packer Manifest
+      id: ami
+      run: |
+        last_run_uuid=$(jq -r '.last_run_uuid' "./packer_manifest.json")
+        build=$(jq -r '.builds[] | select(.packer_run_uuid == "'"$last_run_uuid"'")' "./packer_manifest.json")
+        ami_id=$(echo "$build" | jq -r '.artifact_id' | cut -d':' -f2)
+        echo "ami_id=$ami_id" >> $GITHUB_OUTPUT
+        echo "AMI ID from Packer build: $ami_id"
 
   update-hcp-packer-channel:
     name: Update HCP Packer channel
